### ISSUE TITLE
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE] 

### ISSUE THREAD

**Issue by AndWong** [boundarydevices/android-tests#1]
Why when I run the branch "reboot_app_systemuid" in android4.4.4, it is tip error ,like this 
 " Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE] " ?

**Comment by gibsson** [comment]
It means you haven't signed your application with the platform keys.

Regards,
Gary
